In [57]:
from tensorflow import keras
from keras import layers
import matplotlib.pyplot as plt
import numpy as np

In [212]:
network = keras.Sequential([
    layers.Input(shape=(8,8,1)),
    layers.Conv2D(32, (3, 3), activation='relu', padding='same'),
    layers.Conv2D(32, (3, 3), activation='relu', padding='same'),
    layers.Flatten(),
    layers.Dense(32, activation='relu', kernel_regularizer=keras.regularizers.l2(0.001)),
    layers.Dropout(0.3),

    layers.Dense(1, activation='tanh')
    ])



In [ ]:
data = np.load('../../data/othello_train_data.npz' ,allow_pickle=True)
X_train, y_train = data['X'], data['y']X_train = 
np.where(X_train == 3, 0, X_train)

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 1, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 1, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[2, 1, 1, ..., 1, 1, 2],
        [2, 1, 1, ..., 1, 2, 2],
        [2, 2, 2, ..., 2, 1, 1],
        ...,
        [2, 1, 2, ..., 1, 2, 1],
        [2, 2, 2, ..., 2, 1, 1],
        [2, 2, 1, ..., 1, 0, 2]],

       [[2, 1, 1, ..., 1, 1, 2],
        [2, 1, 1, ..., 1, 2, 2],
        [2, 2, 2, ..., 2, 1, 1],
        ...,
        [2, 1, 2, ..., 

In [221]:
print("Training data shape:", X_train.shape, y_train.shape)
print("-" *10)
for i,_ in enumerate(X_train):
    print(X_train[i])
    print(f'This game winner was {y_train[i]}')



Training data shape: (58880, 8, 8) (58880,)
----------
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 3 2 3 0 0 0]
 [0 0 0 2 2 0 0 0]
 [0 0 3 2 1 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
This game winner was 1
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 3 1 2 0 0 0 0]
 [0 0 3 1 2 0 0 0]
 [0 0 0 2 1 3 0 0]
 [0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
This game winner was 1
[[0 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0]
 [0 0 1 2 3 0 0 0]
 [0 0 0 1 2 3 0 0]
 [0 0 0 2 2 2 0 0]
 [0 0 0 3 0 3 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
This game winner was 1
[[0 0 0 0 0 0 0 0]
 [0 3 0 0 0 0 0 0]
 [0 3 1 2 0 0 0 0]
 [0 0 3 1 2 0 0 0]
 [0 0 3 1 2 2 0 0]
 [0 0 3 1 0 0 0 0]
 [0 0 3 3 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
This game winner was 1
[[0 0 0 0 0 0 0 0]
 [0 3 0 3 0 0 0 0]
 [0 2 2 2 0 3 0 0]
 [0 0 0 1 2 3 0 0]
 [0 0 0 1 2 2 3 0]
 [0 0 0 1 0 3 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
This game winner was 1
[[3 3 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 2 1 2 0 0 0 0]
 [0 0 3 

KeyboardInterrupt: 

In [213]:
network.compile(optimizer=keras.optimizers.Adam(learning_rate=0.001),loss='mse',metrics=['r2_score'])

In [216]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(-1, 1))
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)
X_train = scaler.fit_transform(X_train.reshape(-1, 64)).reshape(-1, 8, 8)
X_val = scaler.transform(X_val.reshape(-1, 64)).reshape(-1, 8, 8)

In [214]:
early_stop = keras.callbacks.EarlyStopping(patience=50, restore_best_weights=True)

history = network.fit(X_train, y_train, epochs=200, batch_size=32,validation_split=0.2,callbacks=[early_stop])

Epoch 1/200
309/309 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.8772 - r2_score: -0.0274 - val_loss: 0.8441 - val_r2_score: -0.0141
Epoch 2/200
309/309 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.8270 - r2_score: 0.0170 - val_loss: 0.8074 - val_r2_score: 0.0294
Epoch 3/200
309/309 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7984 - r2_score: 0.0505 - val_loss: 0.7942 - val_r2_score: 0.0501
Epoch 4/200
309/309 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7640 - r2_score: 0.0887 - val_loss: 0.7897 - val_r2_score: 0.0630
Epoch 5/200
309/309 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7496 - r2_score: 0.1298 - val_loss: 0.7997 - val_r2_score: 0.0587
Epoch 6/200
309/309 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7039 - r2_score: 0.1783 - val_loss: 0.7870 - val_r2_score: 0.0828
Epoch 7/200
309/309 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.6720 - r2_score: 0.2281 - val_loss: 0.8125 - val_r2_score: 0.0589
Epoch 8/200
309/309 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.6450 - r2_score: 0.2769 - val_lo

In [215]:
network.evaluate(X_val, y_val)

97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.8273 - r2_score: 0.0684


[0.7997252345085144, 0.08316934108734131]

In [ ]:
#Uncomment below to save the  model
## network.save("../../models/untrained_model.keras")