In [3]:
from tensorflow import keras
from keras import layers
import matplotlib.pyplot as plt
import numpy as np

In [53]:
network = keras.Sequential([
    layers.Input(shape=(8,8)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(64, activation='relu'),
    layers.Dense(1, activation='tanh')
    ])

network.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten_3 (Flatten)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 64)             │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 64)             │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 8,385 (32.75 KB)

 Trainable params: 8,385 (32.75 KB)

 Non-trainable params: 0 (0.00 B)

In [54]:
network.save("../../models/untrained_model.keras")

In [9]:
network.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [10]:
data = np.load('../../data/othello_train_data.npz' ,allow_pickle=True)
X_train, y_train = data['X'], data['y']

In [ ]:
print("Training data shape:", X_train.shape, y_train.shape)
for i,_ in enumerate(X_train):
    print(X_train[i])
    print(f'This game winner was {y_train[i]}')



[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 1 2 3 0 0]
 [0 0 0 2 2 0 0 0]
 [0 0 0 3 2 3 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
This game winner was 1
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0]
 [0 0 3 1 2 0 0 0]
 [0 0 0 2 1 3 0 0]
 [0 0 0 0 2 1 3 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
This game winner was 1
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 3 0 0 0]
 [0 0 0 1 2 3 0 0]
 [0 0 3 2 1 0 0 0]
 [0 0 0 3 2 2 2 0]
 [0 0 0 0 3 0 3 0]
 [0 0 0 0 0 0 0 0]]
This game winner was 1
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 3 3 3 3 0 0]
 [0 0 0 1 1 1 0 0]
 [0 0 0 2 1 3 0 0]
 [0 0 0 0 2 2 2 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
This game winner was 1
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 3 0 0]
 [0 0 0 0 3 2 0 0]
 [0 0 0 1 2 1 0 0]
 [0 0 3 2 1 0 0 0]
 [0 0 0 3 2 2 2 0]
 [0 0 0 0 3 0 3 0]
 [0 0 0 0 0 0 0 0]]
This game winner was 1
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 3 0 2 0 0]
 [0 0 3 1 2 1 3 0]
 [0 0 0 2 1 3 0 0]
 [0 0 0 0 2 1 2 0]
 [0 0 